services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerized-ecom
    restart: unless-stopped
    volumes:
      - ./ecom/backend:/var/www/html
      # - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dockerized-laravel-network
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ecom
      - DB_USERNAME=ecom
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # nuxt js
  node:
    image: node:lts
    user: "1000:1000"
    working_dir: /app
    volumes:
      - ./ecom/frontend:/app
    environment:
      HOME: /tmp
    profiles: [ "tools" ]

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: dockerized-laravel-webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./ecom/backend:/var/www/html
      # Use a single file mount instead of a directory
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dockerized-laravel-network
    depends_on:
      - app

  # Postgres Database
  db:
    image: postgres:16-alpine
    container_name: dockerized-laravel-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ecom
      - POSTGRES_USER=ecom
      - POSTGRES_PASSWORD=secret
    volumes:
      - dockerized-laravel-data:/var/lib/postgresql/data
    networks:
      - dockerized-laravel-network
    ports:
      - "5432:5432"

  # Redis for Cache and Queue
  redis:
    image: redis:alpine
    container_name: dockerized-laravel-redis
    restart: unless-stopped
    networks:
      - dockerized-laravel-network
    ports:
      - "6379:6379"

# Networks
networks:
  dockerized-laravel-network:
    driver: bridge

# Volumes
volumes:
  dockerized-laravel-data:
    driver: local
